### ISSUE TITLE
Конкурирование нитей

### ISSUE THREAD

**Issue by kstrizhov** [kstrizhov/multithreading_test#1]
@aurusov

Создал java - класс с двумя нитями, пишут числа в `ArrayList`, затем на экран выводится размер массива. Каждой нитью пишу по 1000 значений. В итоге на выходе размер 2000.

Сейчас попробую то же самое со строкой.

**Comment by kstrizhov** [comment]
Длина строки оказалась 2004, а не 2000, как ожидалось. Теперь попробую с локами из `java.util.concurrent.locks`, насколько я понял это аналоги мьютексов.

**Comment by kstrizhov** [comment]
Добавил лок. Теперь длина строки всегда фиксирована. 2000, если инициализировать ее пустой строкой, как в коммите, и 2004, если просто объявить. Почему такая разница?

PS

> Длина строки оказалась 2004, а не 2000, как ожидалось

Тут я еще немного погонял модель перед добавлением лока, иногда вылезали вообще рандомные цифры от 900 с чем то до 2004. Так что там по ходу все действительно портилось конкретно.

**Comment by aurusov** [comment]
Пример выглядит правильным. Как думаешь, разобрался ? Понимаешь что надо защищать данные, а код ? Готов выделить в курсаче защитить объекты, к которым есть доступ сразу из нескольких нитей ?

**Comment by kstrizhov** [comment]
Думаю да. Попробую.
